# Dockerfile
FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# Basic utilities (add more if you need them)
RUN apt-get update



# If you have a local binary, uncomment this
# COPY imessage-query /app/imessage-query
# RUN chmod +x /app/imessage-query

#ENTRYPOINT ["tail"]
#CMD ["-f","/dev/null"]